version: '3.7'

services:
  blog-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: blog-server
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    command: npm run dev
